const initState = {
  NEW: {
    Women: [
      "New Arrivals",
      "Mother's Day Shop",
      "UNIQLO x Marimekko",
      "Hana Tajima",
      "JW Anderson",
      "Uniqlo U",
      "Ines de la Fressange",
    ],
    Men: ["New Arrivals", "JW Anderson", "Uniqlo U"],
    "UT: Graphic Tees": [
      "Daniel Arsham x Pokémon",
      "GUNPLA 40th Anniversary",
      "Neo-Miyage",
      "Disney Princesses and Villains",
      "Anna Su",
    ],
    "Coming Soon": ["Super Mario 5/4"],
  },
  WOMEN: {
    "New Arrivals": [],
    "Best Sellers": [],
    Sale: [],
    Blog: [],
    "Now Trending": [
      "Mother's Day Shop",
      "UNIQLO x Marimekko",
      "Hana Tajima",
      "Daniel Arsham x Pokémon",
      "JW Anderson",
      "Uniqlo U",
    ],
    "Shop By Category": [
      "Outerwear and Blazers",
      "Sweatshirts and Sweatpants",
      "Loungewear",
      "Sweaters and Cardigans",
      "Shirts and Blouses",
      "T-Shirts and Tops",
      "UT: Graphic Tees",
      "Dresses and Jumpsuits",
      "Skirts",
      "Jeans",
      "Pants",
      "Leggings Pants",
      "Shorts",
      "Activewear",
      "Innerwear",
      "Bras and Underwear",
      "Socks and Hosiery",
      "Accessories and Shoes",
    ],
    "Shop By Technology": [
      "BLOCKTECH",
      "UV Protection",
      "3D Knit",
      "Bra Tops",
      "Ultra Light Down Collection",
      "AIRism",
      "HEATTECH Collection",
    ],
    "Shop By Collection": [
      "Sport Utility Wear",
      "Shop For The Better",
      "Travel Shop",
      "Trend Report",
      "Linen Collection",
      "For Students",
      "Maternity",
      "Wear To Work",
      "Extended Sizes",
      "UNIQLO Update",
      "View All",
    ],
  },
  MEN: {
    "New Arrivals": [],
    "Best Sellers": [],
    Sale: [],
    Blog: [],
    "Now Trending": [
      "Mother's Day Shop",
      "Daniel Arsham x Pokémon",
      "GUNPLA 40th Anniversary",
      "Neo-Miyage",
      "JW Anderson",
      "Uniqlo U",
      "Sport Utility Wear",
    ],
    "Shop By Category": [
      "Outerwear and Blazers",
      "Sweatshirts and Sweatpants",
      "Loungewear",
      "Sweaters",
      "Casual Shirts",
      "Dress Shirts",
      "T-Shirts",
      "UT: Graphic Tees",
      "Polo Shirts",
      "Jeans",
      "Pants",
      "Chino Pants",
      "Shorts",
      "Activewear",
      "Undershirts",
      "Underwear",
      "Socks and Tights",
      "Accessories and Shoes",
    ],
    "Shop By Technology": [
      "Kando",
      "BLOCKTECH",
      "UV Protection",
      "DRY-EX",
      "Ultra Light Down Collection",
      "AIRism",
      "HEATTECH Collection",
    ],
    "Shop By Collection": [
      "Shop For The Better",
      "Travel Shop",
      "Style Guide",
      "Linen Collection",
      "For Students",
      "Wear To Work",
      "Extended Sizes",
      "UNIQLO Update",
      "View All >",
    ],
  },
  KIDS: {
    "New Arrivals": [],
    "Best Sellers": [],
    "Buy 2, Get 1 Free UT": [],
    "Limited-Time Offers": [],
    Sale: [],
    "Now Trending": [
      "UNIQLO x Marimekko",
      "Super Mario",
      "LOL Surprise",
      "Daniel Arsham x Pokémon",
      "UV Protection",
      "Activewear",
    ],
    "Shop By Category": [
      "Outerwear",
      "Sweaters",
      "Sweatshirts and Sweatpants",
      "Tops",
      "UT: Graphic Tees",
      "Bottoms",
      "Dresses",
      "Innerwear and Loungewear",
      "Accessories",
    ],
    "Shop By Technology": ["BLOCKTECH", "AIRism", "HEATTECH Collection"],
    "Shop By Collection": ["Online Exclusives", "UNIQLO Updates", "View All >"],
  },
  BABY: {
    "New Arrivals": [],
    "Best Sellers": [],
    "Buy 2, Get 1 Free UT": [],
    Sale: [],
    "Now Trending": [
      "UNIQLO x Marimekko",
      "Finlayson",
      "UV Protection",
      "Bodysuits",
      "Leggings",
    ],
    Newborn: [
      "Shop All (0 - 12M)",
      "Bodysuits",
      "One-Pieces",
      "Leggings",
      "Socks",
    ],
    Toddler: [
      "Shop All (12M - 4Y)",
      "Outerwear",
      "Sweatshirts",
      "Sweaters",
      "T-Shirts",
      "Leggings",
      "Dresses",
      "Pajamas",
      "Undershirts",
      "Socks",
      "Accessories",
    ],
    "Shop By Technology": ["AIRism", "HEATTECH"],
    "Shop By Collection": [
      "Baby Q&A",
      "Maternity",
      "UT: Graphic Tees",
      "Online Exclusives",
      "UNIQLO Update",
      "View All >",
    ],
  },
  ABOUT: {
    "Our Brand": ["This Is LifeWear", "Global Ambassadors", "Work With Us"],
    "Our Story": [
      "UT Magazine",
      "The Art and Science of LifeWear",
      "LifeWear Magazine",
      "Catalog",
      "UNIQLO Masterpiece",
      "Invisible Quality",
      "UNIQLO Update",
      "LifeWear Story 100",
      "UNIQLO Today",
    ],
    "Our Technology": [
      "HEATTECH",
      "AIRism",
      "Ultra Light Down",
      "3D Knit",
      "DRY-EX",
      "Bra Tops",
    ],
    "Our Stores": [
      "NJ American Dream",
      "FL Florida Mall",
      "IL State Street",
      "HI Ala Moana",
      "Store Locator",
    ],
    Sustainability: [
      "Our Mission",
      "Plastic Reduction",
      "All-Product Recycling Initiative",
      "Sustainable Jeans",
      "UN Women Global Partnership",
      "UNIQLO x charity: water",
    ],
  },
};

const menuReducer = (state = initState, action) => {
  return state;
};

export default menuReducer;
